### ISSUE TITLE
Suggest proper cache drivers in README

### ISSUE THREAD

**Issue by mpyw** [mpyw/laravel-cached-database-stickiness#14]
| Driver | Is eligible? | Description |
|:---|:---:|:---|
| `redis` | 😄 | Very fast, scalable and reliable driver | 
| `memcached` | 😄 |  Alternative for Redis | 
| `dynamodb` | 😃 |  It works but not so suitable for short-term caching |
| `apc` | 😧 | It works as long as the PHP container is not redundant | 
| `file` | 😧 | It works as long as the PHP container is not redundant |
| `database` | 🤮 | We'll get into a chicken or egg situation |
| `array` | 🤮 | Just for testing |

---

UPDATED:

| Driver | Is eligible? | Description |
|:---|:---:|:---|
| `redis` | 😄 | Very fast, scalable and reliable driver | 
| `memcached` | 😄 |  Alternative for Redis | 
| `dynamodb` | 😃 |  It works but not so suitable for short-term caching |
| `apc` | 😧 | It works unless PHP processes are running in multiple machines or containers | 
| `file` | 😧 | It works unless PHP processes are running in multiple machines or containers |
| `database` | 🤮 | We'll get into a chicken-or-egg situation |
| `array` | 🤮 | Just for testing |

**Comment by mpyw** [comment]
@chitoku-k Please review my English

**Comment by chitoku-k** [comment]
> It works as long as the PHP container is not redundant

This one does not make sense.

> We'll get into a chicken or egg situation

Use a hyphenated expression for adjectives:

```diff
- We'll get into a chicken or egg situation
+ We'll get into a chicken-or-egg problem
```

**Comment by mpyw** [comment]
@chitoku-k

> This one does not make sense.

Well... How about this?

`It works as long as the PHP processes are not run in multiple machines or containers`

**Comment by chitoku-k** [comment]
@mpyw
I got what you meant:
```diff
- It works as long as the PHP processes are not run in multiple machines or containers
+ It works unless PHP processes are running in multiple machines or containers
```
