### ISSUE TITLE
[Question] Behaviour of Stickiness when using ShouldAssumeFresh

### ISSUE THREAD

**Issue by ocind** [mpyw/laravel-cached-database-stickiness#26]
Thanks for sharing this library! I have been trying to implement a similar thing.

I have a question regarding the usage of  `ShouldAssumeFresh`. Will it disregard `sticky` and `stickiness_ttl` and always revert to the Slave when reading? Or will it be sticky and follow what is specified on `stickiness_ttl`?

Again, thanks for creating this!

**Comment by mpyw** [comment]
Sorry for the late reply. 

> | | General Queueable | `ShouldAssumeFresh` Queueable |
> |:---:|:---:|:---:|
> | `AlwaysModifiedInitializer`<br>**(Default)**| Master | **Slave** |

Assume that you have enabled `stikcy` and you are using the default setting.

- Background job execution is unaffected by `stickiness_ttl` and all individual jobs always refer to master instances.
- For `ShouldAssumeFresh` jobs, it refer to slave instances at the start. if the job makes side-effects, it will refer to master until the job completes.
